const option = {
    Hogar: {
        TipoVivienda: [
            "Casa/ocupación permanente",
            "Country/ocupación permanente",
            "Departamento/ocupación permanente",
            "Vivienda y/o Departamento/ocupación transitoria",
        ],
        Material: [
            "Material",
            "Mat.,Piedra y hasta 50% madera",
            "Construcción en seco",
            "Adobe o similar"
        ],
        Techo:[
            "Tirantería de madera y tejas",
            "Tirantería de madera y zinc",
            "Zinc",
            "Tirantería de madera y paja",
            "Tirantería y tejas de madera",
        ],
        Cerramiento:[
            "Totalmente cerrados",
            "Parcialmente cerrados",
            "Sin cerramiento"
        ],
        Construccion: [
            "Buena",
            "Muy Buena",
            "De Lujo"
        ],
        AntiSismica:[
           "Si",
           "No"
        ]
    },

    Comercio: {
        Construccion: [
            "Todo de material c/techo de loza o chapas",
            "Todo de chapas o paneles metálicos",
            "Construccion de material y techo de madera",
            "Construcción de madera y techo metálico",
        ],
        Cerramiento: [
                "Totalmente cerrados",
                "Hasta 2 costados abiertos",
                "Mas de 2 costados abiertos",
                "Al menos un costado abierto",
                "Totalmente abiertos"
        ],
        Techo: [
            "Techo de loza de hormigón",
            "Techo de zinc, aluminio o teja"
        ],
        Actividad: [
            "Acumuladores y/o baterias",
            "Aguas gaseosas, refrescos y similares",
            "Alfombras y similares",
            "Almacenes de comestibles, bebidas y similares",
            "Antiguedades, casa de venta",
            "Aparatos e instrumental para medicina",
            "Armerías",
            "Automotores - concesionarias con taller de reparación con pintura",
            "Automotores - concesionarias ventas exclusivamente",
            "Autoservicios",
            "Avisos luminosos (taller p/la fabricación de)",
            "Bailes, academia de",
            "Baños y/o masajes, casa de",
            "Bares y cafes",
            "Bazares",
            "Bibliotecas",
            "Bicicletas y sus repuestos",
            "Billares, juegos electrónicos y similares",
            "Bombonerías y similares",
            "Bordados, talleres de",
            "Calzados, talleres de arreglos de",
            "Camisas y ropa blanca, venta de",
            "Cancha de pelota, padel o tenis cubiertas",
            "Cancha de pelota, padel o tenis descubiertas",
            "Carnicería, pescadería y pollería (venta de)",
            "Carpintería metálica",
            "Casas de ventas de vehículos",
            "Casas velatorias",
            "Cerrajería, herrajería, molduras y similares",
            "Cirugía, aparatos e instrumentos para",
            "Colchas, acolchados y similares",
            "Consultorios dentales",
            "Consultorios médicos",
            "Copias helioggráficas y fotocopias, casas de",
            "Cristalerías y locerías",
            "Cuadros casas de ventas",
            "Cuadros exposiciones de",
            "Cuadros, depósito de",
            "Cuchillerías y artículos similares",
            "Droguerías farmaceuticas o veterinarias",
            "Educación, centros educativos",
            "Electricidad y electrónica, articulos de",
            "Electrodomésticos, venta y depósito",
            "Esculturas, pinturas, taller de",
            "Farmacias",
            "Ferreterías",
            "Fiambrerías unicamente",
            "Florerías naturales",
            "Fotograbado, taller de",
            "Fotografía, optica y cinematografía, art. de",
            "Frutería y/o verdulería",
            "Galerías comerciales",
            "Gomerías, talleres de reparación sin recauchutaje",
            "Guardamuebles negocio de",
            "Heladerías",
            "Herboristerías",
            "Hilados, tejidos y telas",
            "Iglesias, templos y similares",
            "Iluminación, art. de",
            "Imprenta (taller de)",
            "Juegos recreativos - No electrónicos en area cubierta",
            "Jugueterías",
            "Kioscos",
            "Laboratorio de análisis",
            "Lácteos, productos en general",
            "Lavaderos de automotores",
            "Lavaderos de ropa, autoservicio",
            "Lencería, mercerías, ropa blanca y similares",
            "Locutorio",
            "Lubricantes, depósito y venta",
            "Máquinas y equipos, y sus repuestos - (Electrónicas)",
            "Máquinas y equipos, y sus repuestos - (Agrícolas)",
            "Máquinas y equipos, y sus repuestos - De uso comercial o fam.",
            "Máquinas y equipos, y sus repuestos - (Industriales)",
            "Marmolerías",
            "Mercados de alimentos en general",
            "Mobiliarios en general",
            "Motocicletas y sus repuestos",
            "Mueblerías de bronce, hierro y demás metales",
            "Mueblerías en general",
            "Música, discos, cassetes, compacts, venta de",
            "Música, instrumentos, venta de",
            "Neumáticos, depósitos y ventas",
            "Oficinas",
            "Orfebrerías",
            "Ortopedia",
            "Panaderías y/o pastelerías con horno",
            "Panaderías y/o pastelerías con horno a leña",
            "Panaderías y/o pastelerías sin horno",
            "Papelerías y librerías",
            "Pastas alimenticias frescas, fabricación y/o venta",
            "Peluquerías",
            "Perfumerías y artículos de tocador",
            "Pinturerías",
            "Pizzerías",
            "Prótesis dentales, taller de",
            "Remates, casas de",
            "Repuestos",
            "Restaurantes y/o casa de comida y similares",
            "Ropa blanca y/o lencería y similares",
            "Rotiserías",
            "Sanitarios, artículos de",
            "Santerías",
            "Sastrerías",
            "Sellos de goma o plástico, fábricas de",
            "Semillerías",
            "Talleres mecánicos con chapa y pintura",
            "Talleres mecánicos sin pintura",
            "Tapicería para muebles",
            "Tapicería para automóviles",
            "Tejidos, telas e hilados, talleres no industriales",
            "Tiendas",
            "Tintorería",
            "Valijas, baules y artículos para viajes",
            "Veterinarias",
            "Vidrieros, negocios y/o depósitos",
            "Vinos y cervezas",
            "Zapaterías y/o zapatillería",

        ]
    }
}

export { option };